services:
  db:
    image: postgres:18.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-admin-db}
    ports:
      - "${POSTGRES_EXT_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgresql_conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    stop_signal: SIGTERM
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-admin-db} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - crm-network

  app:
    build: .
    command: >
      sh -c "python crm/manage.py migrate &&
             python crm/manage.py init_roles &&
             python crm/manage.py collectstatic --noinput &&
             gunicorn --chdir crm crm.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 2"
    # НЕ пробрасываем порт 8000 наружу, так как nginx будет проксировать
    # ports:
    #   - "8000:8000"  # закомментировано - доступ только через nginx
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      DJANGO_DEBUG: "False"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_data:/app/crm/staticfiles
      - media_data:/app/crm/media
    networks:
      - crm-network
    user: "1000:1000"
    stop_grace_period: 30s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # основной вход - 80 порт
      - "443:443"  # если нужен HTTPS, раскомментировать
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/vol/static/
      - media_data:/vol/media/
    depends_on:
      - app
    networks:
      - crm-network
    stop_grace_period: 30s

volumes:
  db_data:
  static_data:
  media_data:

networks:
  crm-network:
    driver: bridge
