[project]
name = "CRM-system"
version = "0.0.1"
description = ""
readme = "README.md"
authors = [
    { name = "Сергей Хомук", email = "homuk.serega@yandex.by" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.2,<7.0.0",
    "python-dotenv>=1.2.2,<2.0.0",
    "psycopg[binary]>=3.3.4,<4.0.0",
    "watchdog>=6.0.0,<7.0.0",
    "django-debug-toolbar>=7.0.0,<8.0.0",
    "gunicorn[standard]>=26.0.0",
    "django-unused-media>=0.2.2",
    "djangorestframework>=3.16.1",
    "drf_spectacular",
]

[dependency-groups]
dev = [
    "pylint>=4.0.6,<5.0.0",
    "pylint-django>=2.8.0",
    "ruff>=0.6.0,<1.0.0",
]

# --- Конфигурация Ruff ---
[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "C4", "SIM", "ARG", "PTH", "RUF"]
ignore = ["E501", "B008", "B904", "RUF012"]

[tool.ruff.lint.isort]
known-first-party = ["crm", "accounts", "products", "ads", "leads", "customers", "contracts"]

[tool.ruff.lint.per-file-ignores]
"*/migrations/*" = ["ALL"]
"*/tests/*" = ["D", "S101"]
"*/models.py" = ["D", "RUF012"]
"manage.py" = ["D", "T201"]
