[project]
name = "CRM-system"
version = "0.0.1"
description = ""
readme = "README.md"
authors = [
    { name = "Сергей Хомук", email = "homuk.serega@yandex.by" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.2,<7.0.0",
    "python-dotenv>=1.2.2,<2.0.0",
    "psycopg[binary]>=3.3.4,<4.0.0",
    "watchdog>=6.0.0,<7.0.0",
    "django-debug-toolbar>=7.0.0,<8.0.0",
    "pylint>=4.0.6,<5.0.0",
    "gunicorn[standard]>=26.0.0",
    "pylint-django>=2.8.0",
    "pre-commit>=4.6.1",
    "django-unused-media>=0.2.2",
]
