# Generated by Django 6.1 on 2026-08-10 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='contracts.contract')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
