# Generated by Django 6.0.7 on 2026-08-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('period', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ManyToManyField(blank=True, null=True, related_name='products', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Contracts',
            },
        ),
    ]
